### ISSUE TITLE
App Shortcuts are overriding OS default shortcuts.

### ISSUE THREAD

**Issue by guilhermeljs** [jordyfontoura/wbe#7]
Tested in: <img src="https://github.com/jordyfontoura/wbe/assets/92823169/4ab2989b-00d1-4ed5-91da-4ca4bd2b01d6" align="center" width="32"/>

What is happening: 
When we have the app opened, and use CTRL + A or other shortcuts outside the app, it will act like we used the shortcut in the app, and the OS default shortcut will not work, even with the app minimized!

How to reproduce:

1. Open the app
2. Try to use CTRL + A outside the app for selecting something (texts or even files in the default explorer)

**Comment by jordyfontoura** [comment]
A [PR](https://github.com/jordyfontoura/wbe/pull/8) has been opened to resolve this issue

https://github.com/jordyfontoura/wbe/pull/8
